name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
  - title: '💄 Styling'
    labels:
      - 'style'
      - 'css'
      - 'ui'
      - 'ux'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes in this release

  $CHANGES

  **Contributors:** Thanks to the following people for contributing to this release:
  $CONTRIBUTORS

  **Full Changelog:** [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/AfrinvestOptimus/afrikit-shared/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'documentation'
  default: patch
