name: Publish npm Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'yarn'

      # Step 3: Configure npm to use the authentication token
      - name: Configure npm to use the token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Step 4: Install dependencies
      - name: Install dependencies
        run: yarn install
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      # Step 5: Build the project
      - name: Build project
        run: yarn build

      # Step 6: Use Lerna to version and publish all updated packages to npm
      - name: Publish packages with Lerna
        run: |
          git config --global user.email "developers@afrinvest.com"
          git config --global user.name "Afrinvest"
          git checkout main
          npx lerna version --conventional-commits --yes --no-private
          npx lerna publish from-package --yes --no-private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Step 7: Push version changes and tags to GitHub only if there are changes
      - name: Check if there are changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes"
          else
            echo "no changes"
          fi

      - name: Commit and push version changes if there are any
        if: steps.changes.outputs.changes == 'changes'
        run: |
          git add .
          git commit -m "Bump versions [skip ci]"
          git push origin HEAD:main
          git push --tags
        env:
          GH_PAT: ${{ secrets.GH_PAT }}