name: Publish npm Package

#one:
#  release:
#    types: [created]

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Configure npm to use the token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: yarn install
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Build project
        run: yarn build

      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"

      - name: Update package.json with new version
        run: |
          jq --arg VERSION "${{ steps.extract_version.outputs.VERSION }}" '.version = $VERSION' package.json > tmp.$$.json && mv tmp.$$.json package.json
          git config --global user.email "developers@afrinvest.com"
          git config --global user.name "Afrinvest"
          git add package.json
          git commit -m "Bump version to ${{ steps.extract_version.outputs.VERSION }}"
          git push origin HEAD:main

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --non-interactive --new-version ${{ steps.extract_version.outputs.VERSION }}

      - name: Push tags
        run: git push --tags
